# Generated by Django 4.2.9 on 2026-03-17 15:37

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Untitled Recording', max_length=255)),
                ('file', models.FileField(help_text='The actual video file (WebM or MP4)', upload_to=api.models.video_upload_path)),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional video thumbnail', null=True, upload_to='thumbnails/')),
                ('duration', models.FloatField(default=0, help_text='Recording duration in seconds')),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('mime_type', models.CharField(default='video/webm', help_text='MIME type of the video file', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who owns this recording', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Recording',
                'verbose_name_plural': 'Video Recordings',
                'ordering': ['-created_at'],
            },
        ),
    ]
